services:
  shortener:
    build:
      context: ../../
      dockerfile: deploy/docker/Dockerfile
      args:
        GOPROXY: "https://goproxy.cn"
        OS_MIRROR: "http://mirrors.tencent.com/debian"
    container_name: shortener
    restart: unless-stopped        
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
      - DATABASE_TYPE=sqlite
    ports:
      - "8080:8080"
    volumes:
      - ./config.toml:/app/config.toml      