# framagit 不支持 Docker in Docker 服务,需要自建 Runner
# https://docs.gitlab.com/user/packages/container_registry/build_and_push_images/
variables:
  CI_DEBUG_SERVICES: "true"
  TZ: Asia/Shanghai
  DOCKER_TLS_CERTDIR: ""
  # TRIGGER_JOB: ""  # 默认不触发任何作业

default:
  image: docker:latest
  # https://docs.gitlab.com/ci/services/
  # services:
  #   - name: docker:dind
  #     variables:
  #       HEALTHCHECK_TCP_PORT: "2375"
  #     command: ["--registry-mirror", "https://docker.m.daocloud.io" ]

.trigger_template:
  rules:
    - if: '$TRIGGER_JOB == ""'
      when: manual
    - if: "$TRIGGER_JOB =~ /\\b$CI_JOB_NAME\\b/"
      when: manual
    - when: never

stages:
  - build
  - test
  
before_script:
  - |   
    echo "DOCKER_TLS_CERTDIR: ${DOCKER_TLS_CERTDIR:-}"
    echo "TZ: ${TZ:-}"
    echo "GOPROXY: ${GOPROXY:-}"
    echo "OS_MIRROR: ${OS_MIRROR:-}"
    echo "REGISTRY_MIRROR: ${REGISTRY_MIRROR:-}"
  - cat /etc/issue
  # - docker info
  - |
    if [ -n "${OS_MIRROR:-}" ]; then
      sed -i.bak "s#dl-cdn.alpinelinux.org#${OS_MIRROR}#g" /etc/apk/repositories
    fi
  - apk update && apk add --no-cache bash jq
  - /bin/bash --login
  - bash --version
  - |
    if [ -n "${REGISTRIES:-}" ]; then
      REGISTRY_CONF=$(echo "$REGISTRIES" | base64 -d)
    fi
  - |
    if [ -z "${REGISTRY_CONF:-}" ]; then
      echo "not found REGISTRIES"
      exit 1
    fi
  - mkdir -p ~/.docker/
  - echo "$REGISTRY_CONF" > ~/.docker/config.json
  - |
    registries=$(jq -r '.auths | to_entries[] | .key' ~/.docker/config.json)
    if [ -z "${registries:-}" ]; then
      echo "not found registries"
      exit 1
    fi
include:
  - local: 'Dockerfile/alpine/build.yml'
  - local: 'Dockerfile/goreleaser/build.yml'
  - local: 'Dockerfile/test.yml'

after_script:
  - bash ./Dockerfile/push.sh   
  - docker images
    