image: docker:latest

services:
  - docker:dind

variables:
  TZ: Asia/Shanghai
  DOCKER_TLS_CERTDIR: ""

# before_script:
#   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"

include:
  - local: 'dockerfile/goreleaser/build.yml'
