stages:
  - build

goreleaser:
  stage: build
  image: docker:latest
  services:
    - name: docker:dind
  artifacts:
    expire_in: 1 d
  script:
    - docker build -t goreleaser-bookworm:latest .
  # tags:
  #   - docker
