goreleaser:
  extends: ".trigger_template"
  stage: build
  artifacts:
    expire_in: 1 d
  script: 
    - |
      docker build -t goreleaser-bookworm:latest \
        -f Dockerfile/goreleaser/Dockerfile \
        --build-arg GOPROXY=${GOPROXY:-https://proxy.golang.org} \
        .