name: Docker-Dev

on:
  push:
    branches:
      - dev*
    paths:
      - docker-bake.hcl
      - "deploy/docker/Dockerfile"
      - ".github/workflows/docker-dev.yml"

env:
  package_name: shortener

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4   
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env: 
          GHCR_SLUG: ghcr.io/${{ github.repository_owner }}/${{ env.package_name }}        
        with:
          images: |
            ${{ env.GHCR_SLUG }}
          labels: |
            org.opencontainers.image.title=Shortener
            org.opencontainers.image.description=Shortener is a URL shortening service.
            org.opencontainers.image.vendor=Jetsung Chan
          tags: |
            dev
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/bake-action@v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: dev
          push: ${{ github.event_name != 'pull_request' }}    
      
      - uses: actions/delete-package-versions@v5
        continue-on-error: true
        with: 
          package-name: ${{ env.package_name }}
          package-type: 'container'
          min-versions-to-keep: 2
          delete-only-untagged-versions: 'true'      
