name: golangci-lint

on:
  push:
    tags:
      - v*
    branches:
      - main
      - dev
  pull_request:

permissions:
  contents: read
  pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          verify: false # disable verifying the configuration since golangci is currently introducing breaking changes in the configuration 
