name: Release

on:
  push:
    tags:
      - "*"
    paths:
      - docker-bake.hcl
      - "deploy/docker/Dockerfile"
      - ".github/workflows/release.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '^1.24'
        check-latest: true
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        # 'latest', 'nightly', or a semver
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}