services:
  __APP_NAME__:
    container_name: __APP_NAME__
    env_file:
      - path: ./.env
        required: false
    hostname: __APP_NAME__
    image: __APP_IMAGE__:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    restart: unless-stopped
